### ISSUE TITLE
throwing errors when used with Feathersjs service functions

### ISSUE THREAD

**Issue by dkebler** [riophae/better-try-catch#1]
I've been using btc for almost a year now without any issue on all kinds of promise returning and async functions both my own and from other modules.

But for some reason (which I have not tracked down) it won't work with the promise returning functions from the service object of feathersjs   https://docs.feathersjs.com/api/services.html  in particular the .find crud function.   Just to be sure I resorted  back to await-to-js and that works no issue.

I am also using esm by JDalton but that can't be the issue as btc has been working fine in source using esm.  It seems something particular to Feathersjs.  Some how btc is not wrapping the function properly.  It's probably dropping part of the prototype??  Anyway I can use await-to-js so it's no biggy if you can't or don't have the time to track this down.

Here is the call that throws the error
```
  [err, res] = await btc(db[col].api.find)({ query: query, paginate:false })
```

here is what .find contains (which might give you a clue)

```
function () {
			var tmp = this._super;

			// Add a new ._super() method that is the same method
			// but either pointing to the prototype method
			// or to the overwritten method
			this._super = (typeof old === 'function') ? old : _super[name];

			// The method only need to be bound temporarily, so we
			// remove it when we're done executing
			var ret = fn.apply(this, arguments);
			this._super = tmp;

			return ret;
		}
```

and 

Here is the error
```
TypeError: Cannot read property 'before' of undefined
    at getHooks (/home/david/AllData/hacking/active-dev-repos/light2/controller/node_modules/@feathersjs/commons/lib/hooks.js:124:39)
    at mixin.(anonymous function) (/home/david/AllData/hacking/active-dev-repos/light2/controller/node_modules/@feathersjs/feathers/lib/hooks.js:53:46)
    at /home/david/AllData/hacking/active-dev-repos/light2/controller/node_modules/uberproto/lib/proto.js:30:17
```

**Comment by riophae** [comment]
Hi David, thanks for using btc!

I have done some research but am not 100% certain about the reason. I guess it's very likely to be related with `this`. You can try:

```js
[err, res] = await btc(db[col].api.find.bind(db[col].api))({ query: query, paginate:false })
```

or:

```js
[err, res] = await btc(db[col].api.find)).call(db[col].api, { query: query, paginate:false })
```

or the simplest:

```js
[err, res] = await btc(() => db[col].api.find({ query: query, paginate:false })))
```

This example should explain the problem:

```js
const obj = {
  fn() {
    return this
  }
}

obj.fn() // => obj

const fn = obj.fn
fn() // => undefined (strict mode) or window
```
